#!/usr/bin/env sh
#MISE description="Check rust code for compilation errors"
#USAGE flag "-p --package <package>" help="Check only the given package"
#USAGE flag "-a --all-features" help="Check with all features enabled"

set -e

set --

if [ -n "${usage_package:-}" ]; then
	set -- "$@" --package "$usage_package"
else
	set -- "$@" --workspace
fi

if [ "${usage_all_features:-}" = "true" ]; then
	set -- "$@" --all-features
fi

cargo check "$@"
